version: "3.8"

services:
  #Это конфигурация Docker Compose для запуска облачной системы управления контейнерами Portainer.
  portainer:
    container_name: portainer
    deploy:
      restart_policy:
        condition: always
        delay: 5s
    image: portainer/portainer-ce:alpine
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      traefik.enable: "true"
      traefik.http.routers.portainer.entrypoints: "websecure"
      traefik.http.routers.portainer.rule: "Host(`docker.${DOMAIN}`)"
      traefik.http.routers.portainer.service: "portainer"
      traefik.http.routers.portainer.tls.certresolver: "letsencrypt"
      traefik.http.services.portainer.loadbalancer.server.port: "9000"
    volumes:
      - "./portainer/data:/data"
      - "/var/run/docker.sock:/var/run/docker.sock"

networks:
  default:
    external: true
    name: $NETWORK
